### ISSUE TITLE
Degobbing struct with time.Time doesn't seem to work

### ISSUE THREAD

**Issue by MarkOtzen** [drosseau/degob#1]
This gob doesn't decode:
```
00000000  3e ff 81 03 01 01 0b 55  73 65 72 53 65 73 73 69  |>......UserSessi|
00000010  6f 6e 01 ff 82 00 01 03  01 08 55 73 65 72 6e 61  |on........Userna|
00000020  6d 65 01 0c 00 01 07 49  73 41 64 6d 69 6e 01 02  |me.....IsAdmin..|
00000030  00 01 06 49 73 73 75 65  64 01 ff 84 00 00 00 10  |...Issued.......|
00000040  ff 83 05 01 01 04 54 69  6d 65 01 ff 84 00 00 00  |......Time......|
00000050  1f ff 82 01 09 61 6e 6f  6e 79 6d 6f 75 73 02 0f  |.....anonymous..|
00000060  01 00 00 00 0e d7 5e ce  8a 2e 16 ec 5c 00 3c 00  |......^.....\.<.|
00000070
```

```
type UserSession struct {
	Username string
	IsAdmin  bool
	Issued   time.Time
}
```
With the error
`failed to decode gob: error: found unexpected delta value when trying to decode type after processing 68 bytes`

But this one does:
```
00000000  32 ff 81 03 01 01 0b 55  73 65 72 53 65 73 73 69  |2......UserSessi|
00000010  6f 6e 01 ff 82 00 01 02  01 08 55 73 65 72 6e 61  |on........Userna|
00000020  6d 65 01 0c 00 01 07 49  73 41 64 6d 69 6e 01 02  |me.....IsAdmin..|
00000030  00 00 00 0e ff 82 01 09  61 6e 6f 6e 79 6d 6f 75  |........anonymou|
00000040  73 00                                             |s.|
00000042
```

```
type UserSession struct {
	Username string
	IsAdmin bool
}
```

**Comment by drosseau** [comment]
The project has moved to Gitlab: https://gitlab.com/drosseau/degob

Sadly this is a known limitation. The gob encoder will use custom `BinaryMarshaler`, `GobMarshaler`, or `TextMarshaler` methods of encoding when they're present. `time.Time` implements these interfaces. These types are entirely opaque. I believe I made a change over in the gitlab project that at least doesn't panic in these instances. https://gitlab.com/drosseau/degob/-/commit/1b00275190b99872a3046bf2edd30851831c24f8

I updated this repository to be in sync with the Gitlab one that has that fix.
